/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.17
 * Generated at: 2018-05-22 16:27:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.apply;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class apply_005fadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/SSM-GY/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/00.08_AssetsManagementSystem/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/D:/SSM-GY/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/00.08_AssetsManagementSystem/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1522309388777L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>添加申请</title>\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/xadmin.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/kkpager_orange.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"lib/layui/css/layui.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"lib/layui/layui.js\" charset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/xadmin.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/kkpager.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(basePath);
      out.write("resources/My97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("<!-- 让IE8/9支持媒体查询，从而兼容栅格 -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://cdn.staticfile.org/html5shiv/r29/html5.min.js\"></script>\r\n");
      out.write("      <script src=\"https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"x-body\">\r\n");
      out.write("\t\t<font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ifo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</font>\r\n");
      out.write("\t\t<form class=\"layui-form\" method=\"post\"\r\n");
      out.write("\t\t\taction=\"applyController/propertyAdd.do\">\r\n");
      out.write("\t\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t\t<label for=\"L_repass\" class=\"layui-form-label\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"x-red\">*</span>类型 </label>\r\n");
      out.write("\t\t\t\t<div class=\"layui-input-inline\">\r\n");
      out.write("\t\t\t\t\t</label> <select name=\"bigtypeName\" id=\"quiz3\" lay-filter=\"myselect2\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">请选择类型</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"固定资产\">固定资产</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"非实物资产\">非实物资产</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"低值易耗损品\">低值易耗损品</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"layui-form-item\" id=\"panel\">\r\n");
      out.write("\t\t\t\t<label for=\"L_repass\" class=\"layui-form-label\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"x-red\">*</span>分类 </label>\r\n");
      out.write("\t\t\t\t<div class=\"layui-input-inline\">\r\n");
      out.write("\t\t\t\t\t<select name=\"malltypeName\" id=\"quiz4\" lay-filter=\"myselect3\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">请选择分类</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"固定资产\">固定资产</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"非实物资产\">非实物资产</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"低值易耗损品\">低值易耗损品</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"layui-form-item\" id=\"panel3\">\r\n");
      out.write("\t\t\t\t<label for=\"L_repass\" class=\"layui-form-label\"><span\r\n");
      out.write("\t\t\t\t\tclass=\"x-red\">*</span>名称 </label>\r\n");
      out.write("\t\t\t\t<div class=\"layui-input-inline\">\r\n");
      out.write("\t\t\t\t\t<select name=\"propertyName\" id=\"quiz1\" lay-filter=\"myselect\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected=\"selected\">请选择资产</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"layui-form-item\" id=\"panel5\">\r\n");
      out.write("\t\t\t\t<label for=\"L_repass\" class=\"layui-form-label\"> <span\r\n");
      out.write("\t\t\t\t\tclass=\"x-red\">*</span>型号\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t<div class=\"layui-input-inline\">\r\n");
      out.write("\t\t\t\t\t<select name=\"type\" id=\"quiz2\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\">请选择型号</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"杭州\">杭州</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"宁波\" disabled=\"\">宁波</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"温州\">温州</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"温州\">台州</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"温州\">绍兴</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t\t<label for=\"L_pass\" class=\"layui-form-label\"> <span\r\n");
      out.write("\t\t\t\t\tclass=\"x-red\">*</span>数量\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t<div class=\"layui-input-inline\">\r\n");
      out.write("\t\t\t\t\t<input name=\"propertyNum\" type=\"text\" id=\"L_pass\"\r\n");
      out.write("\t\t\t\t\t\tautocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"layui-form-item\">\r\n");
      out.write("\t\t\t\t<label for=\"L_repass\" class=\"layui-form-label\"> </label>\r\n");
      out.write("\t\t\t\t<button class=\"layui-btn\" type=\"submit\">提交</button>\r\n");
      out.write("\t\t\t\t<button class=\"layui-btn\" type=\"button\" onclick=\"returnUserApply()\">\r\n");
      out.write("\t\t\t\t\t重置</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t/* layui.use('laydate', function() {\r\n");
      out.write("\t\t\tvar laydate = layui.laydate;\r\n");
      out.write("\t\t\t//执行一个laydate实例\r\n");
      out.write("\t\t\tlaydate.render({\r\n");
      out.write("\t\t\t\telem : '#L_entry' //指定元素\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}); */\r\n");
      out.write("\t\t/* \tfunction addmember() {\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t//提交信息……\r\n");
      out.write("\t\t\t\t\t// 获得frame索引\r\n");
      out.write("\t\t\t\t\tvar index = parent.layer.getFrameIndex(window.name);\r\n");
      out.write("\t\t\t\t\t//关闭当前frame\r\n");
      out.write("\t\t\t\t\tparent.layer.close(index);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} */\r\n");
      out.write("\r\n");
      out.write("\t\tfunction returnUserApply() {\r\n");
      out.write("\t\t\twindow.location.href = \"propertyController/showAllProperty.do\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t/*一級 联动下拉框 */\r\n");
      out.write("\t\t\tlayui.use(['layer', 'form'], function(){\r\n");
      out.write("\t\t\t\t  var layer = layui.layer\r\n");
      out.write("\t\t\t\t  ,form = layui.form;\r\n");
      out.write("\t\t\t\t  form.on('select(myselect2)', function(data){\r\n");
      out.write("\t\t\t\t\t var bigtypeName=$(\"#quiz3\").val();\r\n");
      out.write("\t\t\t\t  $.ajax({\r\n");
      out.write("\t\t                 type: 'POST',\r\n");
      out.write("\t\t                 url: 'propertyController/returnMalltypeName.ajax',\r\n");
      out.write("\t\t                 data: {\r\n");
      out.write("\t\t                \t \"bigtypeName\" : bigtypeName\r\n");
      out.write("\t\t                 },\r\n");
      out.write("\t\t                 dataType:  'json',\r\n");
      out.write("\t\t                 success: function(allproperty){\r\n");
      out.write("\t\t                \t\tvar str = \"\";\r\n");
      out.write("\t\t    \t\t\t\t\t$(\"#quiz4\").empty();\r\n");
      out.write("\t\t    \t\t\t\t\tstr += \"<option>请选择分类</option>\"\r\n");
      out.write("\t\t    \t\t\t\t\t$(\"#quiz4\").html(str);\r\n");
      out.write("\r\n");
      out.write("\t\t    \t\t\t\t\tfor (var i = 0; i < allproperty.length; i++) {\r\n");
      out.write("\t\t    \t\t\t\t\t\tvar property = allproperty[i];\r\n");
      out.write("\t\t    \t\t\t\t\t\t$(\"#quiz4\").append(\"<option >\" + property.malltypeName + \"</option>\");\r\n");
      out.write("\t\t    \t\t\t\t\t\tform.render('select');\r\n");
      out.write("\t\t    \t\t\t\t\t\t $(\"#quiz4\").get(0).selectedIndex=0;\r\n");
      out.write("\t\t    \t\t\t\t\t}\r\n");
      out.write("\t\t                 },\r\n");
      out.write("\t\t                 error : function(msg) {\r\n");
      out.write("\t\t\t    \t\t\t\talert(\"无法连接服务器\");\r\n");
      out.write("\t\t\t    \t\t\t}   \r\n");
      out.write("\t\t         }); \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t/*二級 联动下拉框 */\r\n");
      out.write("\t\t\tlayui.use(['layer', 'form'], function(){\r\n");
      out.write("\t\t\t\t  var layer = layui.layer\r\n");
      out.write("\t\t\t\t  ,form = layui.form;\r\n");
      out.write("\t\t\t\t  form.on('select(myselect3)', function(data){\r\n");
      out.write("\t\t\t\t\t var malltypeName=$(\"#quiz4\").val();\r\n");
      out.write("\t\t\t\t  $.ajax({\r\n");
      out.write("\t\t                 type: 'POST',\r\n");
      out.write("\t\t                 url: 'propertyController/returnPropertyName.ajax',\r\n");
      out.write("\t\t                 data: {\r\n");
      out.write("\t\t                \t \"malltypeName\" : malltypeName\r\n");
      out.write("\t\t                 },\r\n");
      out.write("\t\t                 dataType:  'json',\r\n");
      out.write("\t\t                 success: function(allproperty){\r\n");
      out.write("\t\t                \t\tvar str = \"\";\r\n");
      out.write("\t\t    \t\t\t\t\t$(\"#quiz1\").empty();\r\n");
      out.write("\t\t    \t\t\t\t\tstr += \"<option>请选择资产</option>\"\r\n");
      out.write("\t\t    \t\t\t\t\t$(\"#quiz1\").html(str);\r\n");
      out.write("\r\n");
      out.write("\t\t    \t\t\t\t\tfor (var i = 0; i < allproperty.length; i++) {\r\n");
      out.write("\t\t    \t\t\t\t\t\tvar property = allproperty[i];\r\n");
      out.write("\t\t    \t\t\t\t\t\t$(\"#quiz1\").append(\"<option >\" + property.propertyName + \"</option>\");\r\n");
      out.write("\t\t    \t\t\t\t\t\tform.render('select');\r\n");
      out.write("\t\t    \t\t\t\t\t\t $(\"#quiz1\").get(0).selectedIndex=0;\r\n");
      out.write("\t\t    \t\t\t\t\t}\r\n");
      out.write("\t\t                 },\r\n");
      out.write("\t\t                 error : function(msg) {\r\n");
      out.write("\t\t\t    \t\t\t\talert(\"无法连接服务器\");\r\n");
      out.write("\t\t\t    \t\t\t}   \r\n");
      out.write("\t\t         }); \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t/*三級 联动下拉框 */\r\n");
      out.write("\t\t\tlayui.use(['layer', 'form'], function(){\r\n");
      out.write("\t\t\t\t  var layer = layui.layer\r\n");
      out.write("\t\t\t\t  ,form = layui.form;\r\n");
      out.write("\t\t\t\t  form.on('select(myselect)', function(data){\r\n");
      out.write("\t\t\t\t\t var propertyName=$(\"#quiz1\").val();\r\n");
      out.write("\t\t\t\t  $.ajax({\r\n");
      out.write("\t\t                 type: 'POST',\r\n");
      out.write("\t\t                 url: 'applyController/returnType.do',\r\n");
      out.write("\t\t                 data: {\r\n");
      out.write("\t\t                \t \"propertyName\" : propertyName\r\n");
      out.write("\t\t                 },\r\n");
      out.write("\t\t                 dataType:  'json',\r\n");
      out.write("\t\t                 success: function(allproperty){\r\n");
      out.write("\t\t                \t\tvar str = \"\";\r\n");
      out.write("\t\t    \t\t\t\t\t$(\"#quiz2\").empty();\r\n");
      out.write("\t\t    \t\t\t\t\tstr += \"<option>请选择型号</option>\"\r\n");
      out.write("\t\t    \t\t\t\t\t$(\"#quiz2\").html(str);\r\n");
      out.write("\r\n");
      out.write("\t\t    \t\t\t\t\tfor (var i = 0; i < allproperty.length; i++) {\r\n");
      out.write("\t\t    \t\t\t\t\t\tvar property = allproperty[i];\r\n");
      out.write("\t\t    \t\t\t\t\t\t$(\"#quiz2\").append(\"<option >\" + property.type + \"</option>\");\r\n");
      out.write("\t\t    \t\t\t\t\t\tform.render('select');\r\n");
      out.write("\t\t    \t\t\t\t\t\t $(\"#quiz2\").get(0).selectedIndex=0;\r\n");
      out.write("\t\t    \t\t\t\t\t}\r\n");
      out.write("\t\t                 },\r\n");
      out.write("\t\t                 error : function(msg) {\r\n");
      out.write("\t\t\t    \t\t\t\talert(\"无法连接服务器\");\r\n");
      out.write("\t\t\t    \t\t\t}   \r\n");
      out.write("\t\t         }); \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
