/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.17
 * Generated at: 2018-05-08 02:52:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.UserManger;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/SSM-GY/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/00.08_AssetsManagementSystem/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1522309388777L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<base href=\"");
      out.print(basePath);
      out.write("\" />\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>企业资产管理系统</title>\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit|ie-comp|ie-stand\"/>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"/>\r\n");
      out.write("<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/xadmin.css\">\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"lib/layui/layui.js\"\r\n");
      out.write("\tcharset=\"utf-8\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/xadmin.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"x-body\">\r\n");
      out.write("        <form id=\"form1\" class=\"layui-form\">\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"username\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>姓名\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"text\" id=\"username\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"userName\" required=\"\" lay-verify=\"required\"\r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"username\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>性别\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input name=\"userSex\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userSex=='男'? 'checked':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("  type=\"radio\" value=\"男\" lay-skin=\"primary\" title=\"男\">\r\n");
      out.write("                  <input name=\"userSex\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userSex=='女'? 'checked':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" type=\"radio\" value=\"女\" lay-skin=\"primary\" title=\"女\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"phone\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>手机\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"text\" id=\"phone\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userTelephone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"userTelephone\" required=\"\" lay-verify=\"phone\"\r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"phone\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>电子邮箱\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"text\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userEmail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"userEmail\" required=\"\" lay-verify=\"email\"\r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"username\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>家庭地址\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userAddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  name=\"userAddress\" required=\"\" lay-verify=\"required\"\r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"username\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>出生日期\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"text\" id=\"date1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userBirthday }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"userBirthday\" required=\"\" lay-verify=\"required\"\r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"username\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>入职时间\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"text\" id=\"date2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userEntrytime }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"userEntrytime\" required=\"\" lay-verify=\"required\"\r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"username\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>学历\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <select id=\"shipping\" name=\"userDiploma\" class=\"valid\">\r\n");
      out.write("                    <option value=\"大专\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userDiploma=='大专'?'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" >大专</option>\r\n");
      out.write("                    <option value=\"本科\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userDiploma=='本科'?'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">本科</option>\r\n");
      out.write("                    <option value=\"硕士\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userDiploma=='硕士'?'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">硕士</option>\r\n");
      out.write("                    <option value=\"博士\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userDiploma=='博士'? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">博士</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"username\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>部门安排\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <select name=\"userDepartement\">\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_email\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>职位\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"text\" id=\"L_email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userPosition }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"userPosition\" required=\"\" lay-verify=\"\"\r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("           <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_username\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>账号\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input type=\"text\" id=\"userAccount\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.accountNumber }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"accountNumber\" required=\"\" onchange=\"onlyUser(this)\" lay-verify=\"nikename\"\r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"account\" class=\"layui-form-mid layui-word-aux\">\r\n");
      out.write("                 \t至少3个字符\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("             <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_pass\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>重置密码\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                 <input type=\"checkbox\" name=\"zzz\" lay-filter=\"filter\" lay-skin=\"switch\" lay-text=\"确定|取消\">\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("            <div name=\"pwd\" class=\"layui-form-item \">\r\n");
      out.write("              <label for=\"L_pass\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>新密码\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input onchange=\"safePW()\" type=\"password\" id=\"L_pass\"   \r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("              <div id=\"password\" class=\"layui-form-mid layui-word-aux \">\r\n");
      out.write("                  至少6个字符\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div name=\"pwd\" class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_repass\" class=\"layui-form-label\">\r\n");
      out.write("                  <span class=\"x-red\">*</span>确认密码\r\n");
      out.write("              </label>\r\n");
      out.write("              <div class=\"layui-input-inline\">\r\n");
      out.write("                  <input onchange=\"confirm()\" type=\"password\" id=\"L_repass\" name=\"repass\"  \r\n");
      out.write("                  autocomplete=\"off\" class=\"layui-input\">\r\n");
      out.write("              </div>\r\n");
      out.write("               <div id=\"confire\" class=\"layui-form-mid layui-word-aux \">\r\n");
      out.write("                  \t两次密码必须一致\r\n");
      out.write("              </div> \r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"layui-form-item\">\r\n");
      out.write("              <label for=\"L_repass\" class=\"layui-form-label\">\r\n");
      out.write("              </label>\r\n");
      out.write("              <button  class=\"layui-btn\" lay-filter=\"add\" lay-submit=\"\">\r\n");
      out.write("                  确定\r\n");
      out.write("              </button>\r\n");
      out.write("              <a  class=\"layui-btn\" onclick=\"x_admin_close()\"  lay-submit=\"\">\r\n");
      out.write("                  返回\r\n");
      out.write("              </a>\r\n");
      out.write("          </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("    \r\n");
      out.write("    $(function(){\r\n");
      out.write("\t\tif($(\"#date2\").val()!=\"\"){\r\n");
      out.write("\t\t\t$(\"#date2\").val(new Date($(\"#date2\").val()).format(\"yyyy-MM-dd\"));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"div [name='pwd']\").hide();\r\n");
      out.write("\t\tif($(\"#date1\").val()!=\"\"){\r\n");
      out.write("\t\t\t$(\"#date1\").val(new Date($(\"#date1\").val()).format(\"yyyy-MM-dd hh:mm:ss\"))\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("    \tfunction onlyUser(doms){\r\n");
      out.write("    \t\tif($(\"#userAccount\").val().length<3){\r\n");
      out.write("    \t\t\t$(\"#userAccount\").select();\r\n");
      out.write("    \t\t\t$(\"#account\").html(\"至少3个字符\");\r\n");
      out.write("    \t\t}else{\r\n");
      out.write("    \t\t\tAccountAjax();\r\n");
      out.write("    \t\t}\t\t\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tfunction safePW(){\r\n");
      out.write("\t\t\tif($('#L_pass').val().length>5){\r\n");
      out.write("\t\t\t\t$(\"#password\").html(\"<i class=\\\"layui-icon layui-anim layui-anim-scale \\\" style=\\\"color: #1E9FFF;\\\">&#xe618;</i>\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction confirm(){\r\n");
      out.write("\t\t\tif($('#L_pass').val()==$('#L_repass').val()){\r\n");
      out.write("                  $(\"#confire\").html(\"<i class=\\\"layui-icon layui-anim layui-anim-scale \\\" style=\\\"color: #1E9FFF;\\\">&#xe618;</i>\") \r\n");
      out.write("                }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction AccountAjax(){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\taccount:$(\"#userAccount\").val()\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\t\turl : \"manageEmeController//isRepeat.ajax\",\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\t\tif(result==\"NO\"){\r\n");
      out.write("\t\t\t\t\t\t$(\"#account\").html(\"<i class=\\\"layui-icon layui-anim  layui-anim-scale\\\" style=\\\"color: #1E9FFF;\\\">&#xe618;</i>  \")\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(\"#userAccount\").select();\r\n");
      out.write("\t\t\t\t\t\t$(\"#account\").html(\"<span style=\\\"color: #FF5722\\\" class=\\\"layui-anim layui-anim-scale\\\">账号已存在!</span>\")\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function() {\r\n");
      out.write("\t\t\t\t\t$(\"#userAccount\").select();\r\n");
      out.write("\t\t\t\t\t$(\"#account\").html(\"<span style=\\\"color: #FF5722\\\" class=\\\"layui-anim layui-anim-scale\\\">无法连接服务器!</span>\")\r\n");
      out.write("\t\t\t\t\tlayer.msg('无法连接服务器', {icon: 2});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tlayui.use(['form','layer','laydate'], function(){\r\n");
      out.write("            $ = layui.jquery;\r\n");
      out.write("          var form = layui.form\r\n");
      out.write("          ,layer = layui.layer\r\n");
      out.write("          ,laydate=layui.laydate;\r\n");
      out.write("        \t\r\n");
      out.write("        \t\r\n");
      out.write("          //日期\r\n");
      out.write("          laydate.render({\r\n");
      out.write("    \t\telem: '#date1'\r\n");
      out.write("  \t\t});\r\n");
      out.write("        laydate.render({\r\n");
      out.write("    \t\telem: '#date2'\r\n");
      out.write("  \t\t});\r\n");
      out.write("          //自定义验证规则\r\n");
      out.write("          form.verify({\r\n");
      out.write("            nikename: function(value){\r\n");
      out.write("              if(value.length < 5){\r\n");
      out.write("                return '昵称至少得5个字符啊';\r\n");
      out.write("              }\r\n");
      out.write("            }\r\n");
      out.write("            ,pass: [/(.+){6,12}$/, '密码必须6到12位']\r\n");
      out.write("            ,repass: function(value){\r\n");
      out.write("                if($('#L_pass').val()!=$('#L_repass').val()){\r\n");
      out.write("                    return '两次密码不一致';\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("          });\r\n");
      out.write("          //switch\r\n");
      out.write("          form.on('switch(filter)', function(data){\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\tconsole.log(data.elem.checked); //开关是否开启，true或者false\r\n");
      out.write("  \t\t\tif(!data.elem.checked){\r\n");
      out.write("  \t\t\t\t$(\"#L_pass\").removeAttr(\"lay-verify\");\r\n");
      out.write("  \t\t\t\t$(\"#L_repass\").removeAttr(\"lay-verify\");\r\n");
      out.write("  \t\t\t\t$(\"#L_repass\").removeAttr(\"name\");\r\n");
      out.write("  \t\t\t}else{\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("  \t\t\t\t$(\"#L_pass\").attr(\"lay-verify\",\"pass\");\r\n");
      out.write("  \t\t\t\t$(\"#L_repass\").attr(\"lay-verify\",\"repass\");\r\n");
      out.write("  \t\t\t\t$(\"#L_repass\").attr(\"name\",\"password\");\r\n");
      out.write("  \t\t\t\t\r\n");
      out.write("          \tconsole.log(\"ssss\"+$(\"#L_repass\").prop(\"name\")+\"///\"+$(\"#L_repass\").attr(\"name\"))\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t\t$(\"div [name='pwd']\").toggle(300);\r\n");
      out.write("  \t\t\t\r\n");
      out.write("}); \r\n");
      out.write("          //监听提交\r\n");
      out.write("          form.on('submit(add)', function(data){\r\n");
      out.write("            console.log(data);\r\n");
      out.write("            //发异步，把数据提交给php\r\n");
      out.write("            console.log(data);\r\n");
      out.write("            $.ajax({\r\n");
      out.write("        \t\ttype : \"POST\",\r\n");
      out.write("        \t\tdata : $('#form1').serialize(),\r\n");
      out.write("        \t\tdataType : \"text\",\r\n");
      out.write("        \t\turl :\"manageEmeController/userChanged.ajax?userId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("        \t\tsuccess : function(result) {\r\n");
      out.write("        \t\t //发异步，把数据提交给php\r\n");
      out.write("                 layer.msg(\"修改成功\",{\r\n");
      out.write("              \t\ticon : 1,\r\n");
      out.write("               \t\ttime: 500,\r\n");
      out.write("               \t},function () {\r\n");
      out.write("                     // 获得frame索引\r\n");
      out.write("                     var index = parent.layer.getFrameIndex(window.name);\r\n");
      out.write("                     //关闭当前frame\r\n");
      out.write("                     parent.location.reload();\r\n");
      out.write("                     parent.layer.close(index);\r\n");
      out.write("                 });\r\n");
      out.write("        \t\t},\r\n");
      out.write("        \t\terror : function() {\r\n");
      out.write("        \t\t\tlayer.msg('无法连接服务器', {icon: 2});\r\n");
      out.write("        \t\t}\r\n");
      out.write("        \t});   \r\n");
      out.write("            return false;\r\n");
      out.write("          });\r\n");
      out.write("          });\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("    <script>var _hmt = _hmt || []; (function() {\r\n");
      out.write("        var hm = document.createElement(\"script\");\r\n");
      out.write("        hm.src = \"https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190\";\r\n");
      out.write("        var s = document.getElementsByTagName(\"script\")[0];\r\n");
      out.write("        s.parentNode.insertBefore(hm, s);\r\n");
      out.write("      })();</script>\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /view/UserManger/userEdit.jsp(112,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/view/UserManger/userEdit.jsp(112,20) '${departs}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${departs}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /view/UserManger/userEdit.jsp(112,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("depart");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("              \t\t<option ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userDepartement==depart.departId? 'selected':'' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depart.departId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${depart.departName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </option>\r\n");
          out.write("              ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
